### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nladuo/KB-PM#1]
I would like to point out that identifiers like "[`__CLIENT_H`](https://github.com/nladuo/KB-PM/blob/2bae0b255070bb6d740f1635b687373455e6bb11/src/client.h#L26)" and "[`__PROCESS_H`](https://github.com/nladuo/KB-PM/blob/2bae0b255070bb6d740f1635b687373455e6bb11/src/process.h#L25)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by nladuo** [comment]
Thank for your advice. I am just a novice about linux programing. And I writed the code just for studying and practicing linux c programing. So the code may be somewhat inexperienced and standard.
I will modified it soon.

**Comment by nladuo** [comment]
I have changed identifiers like "__CLIENT_H" to "KBPM_CLIENT_H". Is it okay?

**Comment by elfring** [comment]
Yes. - [The longer name pattern](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) will [reduce the probability for name clashes](https://en.wikipedia.org/wiki/Include_guard#Difficulties) reasonably.
