### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [nladuo/KB-PM#2]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/nladuo/KB-PM/blob/f2e8cf9a65894e9d4861684547640926babd658d/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by nladuo** [comment]
Thank for your advice. I have added CMakeLists.txt for generate makefile.

**Comment by elfring** [comment]
Thanks for [your addition of a higher level build script](https://github.com/nladuo/KB-PM/commit/37816df0c5bb9569455893621c061f46a24e823e).
